### PR TITLE
Use Github Actions

### PR DESCRIPTION
**Pull request by dwfreed**
One possible addition to this would be a problem matcher that will automatically annotate lines with compiler output.

### CODE REVIEW

**Comment by dwfreed** [comment]
Travis will never finish because I killed the .travis.yml in this PR.

**Review by xfnw — APPROVED** [review]
huh weird, the github actions passing badge is a slightly minty-er shade of green than the old travis one

looks good though

**Comment by swantzter** [comment]
I noticed we generate html for the oper guide (and I've had the thought in the back of my head for a bit anyways) maybe it's worth considering building and publishing the oper guide to the site? (it'd be a separate issue ofc)

**Comment by edk0** [comment]
> I noticed we generate html for the oper guide (and I've had the thought in the back of my head for a bit anyways) maybe it's worth considering building and publishing the oper guide to the site? (it'd be a separate issue ofc)

Not until it's updated

**Comment by swantzter** [comment]
> Not until it's updated

Obviously, meant it more as a "sometimes in the future" thing

**Review by edk0 — APPROVED** [review]

**Pull request merged**
